### ISSUE TITLE
Which device tree?

### ISSUE THREAD

**Issue by musisat** [darwin-on-arm/wiki#2]
Hi. I am trying to build Darwin using qemu by following your instructions. I am wondering what the source of the device tree is in this instruction:

```
# Create device tree IMG3
image3maker -t xmdt -f ../DeviceTrees/armpba8.* -o images/DeviceTree.img3
```

No previous instruction mentioned how these Device Trees get here. I could clone the Device Trees repository here, but I am not sure if that provides the correct device tree, or if this is found somewhere else.

**Comment by b-man** [comment]
Hello @musisat, sorry for the delayed response.

Unfortunately that information isn't complete because I am still working on a cleaner approach to implementing device tree support within the bootloader. For now I would recommend using the xmdt.img3 file found within GenericBooter-old as that one is compatible with qemu's emulated realview-pb-a8 board. However, if you wish/need to create a device tree yourself you will need to clone and compile dtc-AppleDeviceTree, add the directory containing the built binaries to your PATH, clone the DeviceTrees repo, and run make to build a fresh set of xml device trees.

**Comment by musisat** [comment]
Thanks. The xmdt.img3 file works. I haven't tried dtc-AppleDeviceTree yet.

**Comment by musisat** [comment]
It also seems to work by running make in the DeviceTrees repository to build a new device tree. I don't see why I need dtc-AppleDeviceTree.

**Comment by b-man** [comment]
@musisat

dtc-AppleDeviceTree has been modified to output device trees in a format that apple's device tree parser can understand. Attempting to boot Darwin with those binary device trees from stock dtc will likely cause problems.

**Comment by stonestrong** [comment]
xmdt.img3 seems not work :( I renamed xmdt.img3 to DeviceTree.img3, and recompile the genericBooter, assertion failed in the prepare_devicetree() function
